Standard error codes.

diff --git a/sdc-inst b/sdc-inst
--- a/sdc-inst
+++ b/sdc-inst
@@ -6,6 +6,13 @@
 # please refer to https://docs.wildlife.systems, or for more information on
 # the project itself, please refer to https://wildlife.systems.
 
+# Return codes
+#
+# Further information on WildlifeSystems standard reurn codes can be found
+# at https://docs.wildlife.systems/return-codes.html
+# 0 - Success
+# 30 - Unsupported device
+
 case "$1" in
         list)
                 echo "none           None"
@@ -101,7 +108,7 @@ case "$1" in
                 ;;
         *)
                 echo "$1 is not supported."
-                exit 1
+                exit 30
 
                 ;;
 esac
